name: send image to DockerHub

on:
  workflow_dispatch:

jobs:
  build-et-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image Docker
        run: docker build -t portfolio-test .

      - name: Run container
        run: docker run -d --name portfolio -p 3000:3000 portfolio-test

      - name: Wait for app to be ready
        run: sleep 10

      - name: Test HTTP response
        run: curl -f http://localhost:3000

      - name: Connexion Ã  DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et push de l'image Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest